services:
  - type: web
    name: truthbot-ai
    env: python
    region: frankfurt
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: SERPER_API_KEY
        sync: false
      - key: HUGGINGFACE_API_KEY
        sync: false
      - key: USE_HUGGINGFACE
        value: "true"
      - key: PYTHON_VERSION
        value: "3.11.0"
